apiVersion: v1
kind: Service
metadata:
  name: minikube-client
  labels:
    app: minikube-client
spec:
  type: NodePort
  ports:
    - port: 1112
      protocol: TCP
      targetPort: 1112
  selector:
    app: minikube-client